name: conradoakey
favicon: null
layout_spectrum: 0.2611714347731322
typography_spectrum: 0.5835700600873679
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.4122428062837571
  lightness: 0.8679175348952413
  saturation: 0.33684149966575205
  rhythmicContrast: 0.2785371884237975
purpose: []
